openapi: 3.0.0
info:
  version: "v1"
  title: 'WSO2 Identity Server - Webhook Management API Definition'
  description: 'This document specifies a **RESTful API** for **WSO2 Identity Server Webhook Subscription Management**'
servers:
  - url: 'https://{server-url}/t/{tenant-domain}/api/server/v1'
    variables:
      server-url:
        default: localhost:9443
      tenant-domain:
        default: carbon.super

security:
  - BasicAuth: []
  - OAuth2: []

paths:
  /webhooks:
    get:
      summary: List webhooks
      description: 'List all webhooks. \n\n <b>Scope(Permission) required:</b> `internal_webhook_view` \n\n'
      operationId: getWebhooks
      tags:
        - Webhooks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookList'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        x-codeSamples:
          - lang: Curl
            source: |
              curl --location 'https://localhost:9443/t/carbon.super/api/server/v1/webhooks' -H 'Authorization: Basic YWRtaW46YWRtaW4='

    post:
      summary: Add webhook
      description: 'Create a new webhook subscription. \n\n <b>Scope(Permission) required:</b> `internal_webhook_create` \n\n'
      operationId: createWebhook
      tags:
        - Webhooks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequest'
      responses:
        '201':
          description: Webhook Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        x-codeSamples:
          - lang: Curl
            source: |
              curl --location --request POST 'https://localhost:9443/t/carbon.super/api/server/v1/webhooks' \
              -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
              -H 'Content-Type: application/json' \
              -d '{
                "endpoint": "https://example.com/webhook",
                "description": "Webhook for login events",
                "secret": "my-secret",
                "events_requested": ["schemas.identity.wso2.org/events/logins/event-type/loginSuccess", "schemas.identity.wso2.org/events/logins/event-type/loginFailed"]
              }'

  /webhooks/{webhookId}:
    get:
      summary: Retrieve a webhook by ID
      description: 'Get a webhook specified by webhook ID. \n\n <b>Scope(Permission) required:</b> `internal_webhook_view` \n\n'
      operationId: getWebhook
      tags:
        - Webhooks
      parameters:
        - name: webhookId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Webhook not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        x-codeSamples:
          - lang: Curl
            source: |
              curl --location 'https://localhost:9443/t/carbon.super/api/server/v1/webhooks/101' -H 'Authorization: Basic YWRtaW46YWRtaW4='

    put:
      summary: Update a webhook
      description: 'Update a webhook by webhook ID. \n\n <b>Scope(Permission) required:</b> `internal_webhook_update` \n\n'
      operationId: updateWebhook
      tags:
        - Webhooks
      parameters:
        - name: webhookId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequest'
      responses:
        '200':
          description: Webhook Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Webhook not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        x-codeSamples:
          - lang: Curl
            source: |
              curl --location --request PUT 'https://localhost:9443/t/carbon.super/api/server/v1/webhooks/101' \
              -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
              -H 'Content-Type: application/json' \
              -d '{
                "endpoint": "https://example.com/webhook",
                "description": "Webhook for login events",
                "secret": "my-secret",
                "events_requested": ["schemas.identity.wso2.org/events/logins/event-type/loginSuccess", "schemas.identity.wso2.org/events/logins/event-type/loginFailed"]
              }'

    delete:
      summary: Delete a webhook
      description: 'Delete a webhook by webhook ID. \n\n <b>Scope(Permission) required:</b> `internal_webhook_delete` \n\n'
      operationId: deleteWebhook
      tags:
        - Webhooks
      parameters:
        - name: webhookId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Webhook Deleted
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Webhook not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        x-codeSamples:
          - lang: Curl
            source: |
              curl --location --request DELETE 'https://localhost:9443/t/carbon.super/api/server/v1/webhooks/101' -H 'Authorization: Basic YWRtaW46YWRtaW4='

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://localhost:9443/oauth2/authorize'
          tokenUrl: 'https://localhost:9443/oauth2/token'
          scopes:
            internal_webhook_view: View webhooks
            internal_webhook_create: Create webhooks
            internal_webhook_update: Update webhooks
            internal_webhook_delete: Delete webhooks

  schemas:
    WebhookRequest:
      type: object
      required:
        - endpoint
        - eventSchema
        - description
        - eventsRequested
      properties:
        endpoint:
          type: string
          description: Webhook URL.
          example: https://example.com/webhook
        eventSchema:
          type: string
          example: 'WSO2'
        description:
          type: string
          description: Webhook description.
          example: A webhook for user events.
        secret:
          type: string
          description: Secret for validating webhook payloads.
          example: my-secret
        eventsRequested:
          type: array
          items:
            type: string
          description: List of events to subscribe to.
          example: ["schemas.identity.wso2.org/events/logins/event-type/loginSuccess", "schemas.identity.wso2.org/events/logins/event-type/loginFailed"]

    WebhookResponse:
      allOf:
        - type: object
          properties:
            id:
              type: integer
              example: 101
            createdAt:
              type: string
              format: date-time
              example: '2024-05-01T12:00:00Z'
            updatedAt:
              type: string
              format: date-time
              example: '2024-05-02T12:00:00Z'
            endpoint:
              type: string
              description: Webhook URL.
              example: https://example.com/webhook
            eventSchema:
              type: string
              example: 'WSO2'
            description:
              type: string
              description: Webhook description.
              example: A webhook for user events.
            eventsRequested:
              type: array
              items:
                type: string
              description: List of events to subscribe to.
              example: ["schemas.identity.wso2.org/events/logins/event-type/loginSuccess", "schemas.identity.wso2.org/events/logins/event-type/loginFailed"]

    WebhookList:
      type: object
      properties:
        webhooks:
          type: array
          items:
            $ref: '#/components/schemas/WebhookResponse'

    Error:
      type: object
      properties:
        code:
          type: string
          example: WEBHOOK-00001
        message:
          type: string
          example: Some error message.
        description:
          type: string
          example: Some error description.
        traceId:
          type: string
          example: e0fbcfeb-3617-43c4-8dd0-7b7d38e13047
