openapi: 3.0.0
info:
  title: Asynchronous Operation Status API Definition
  description: This API provides administrators with the ability to get the completion status of asynchronous operations.
  contact:
    name: WSO2
    url: http://wso2.com/products/identity-server/
    email: iam-dev@wso2.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: "https://{server-url}/t/{tenant-domain}/api/server/v1"
  variables:
    tenant-domain:
      default: carbon.super
    server-url:
      default: localhost:9443
paths:
  /async-operation-status/subject-types/{operationSubjectType}/subject/{operationSubjectId}/operation-type/{operationType}:
    description: Asynchronous Operation Detail
    get:
      description: Obtain list of all the asynchronous operations.
      parameters:
      - name: operationSubjectType
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: APPLICATION
      - name: operationSubjectId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 23d7ab3f-023e-43ba-980b-c0fd59aeacf9
      - name: operationType
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: B2B_APPLICATION_SHARE
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationRecords'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    OperationRecords:
      type: array
      items:
        $ref: '#/components/schemas/OperationRecords_inner'
    Error:
      type: object
      properties:
        code:
          type: string
          example: AAA-00000
        message:
          type: string
          example: Some error message.
        description:
          type: string
          example: Some error description.
        traceId:
          type: string
          example: e0fbcfeb-3617-43c4-8dd0-7b7d38e13047
    OperationRecords_inner:
      properties:
        operationId:
          type: string
          example: "56"
        operationType:
          type: string
          example: B2B_APPLICATION_SHARE
        operationSubjectType:
          type: string
          example: B2B_APPLICATION
        operationSubjectId:
          type: string
          example: 23d7ab3f-023e-43ba-980b-c0fd59aeacf9
        residentOrgId:
          type: string
          example: 10084a8d-113f-4211-a0d5-efe36b082211
        initiatorId:
          type: string
          example: 53c191dd-3f9f-454b-8a56-9ad72b5e4f30
        operationStatus:
          type: string
          example: SUCCESS
        operationPolicy:
          type: string
          example: SHARE_WITH_ALL
