swagger: '2.0'
info:
  version: v1
  title: WorkFlow Engine (Removed from API)
  description: This is the RESTful API for managing WorkFlow Engines in WSO2 Identity Server
  contact:
    name: "WSO2 Identity Server"
    url: "https://wso2.com/identity-and-access-management/"
    email: "architecture@wso2.com"
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

schemes:
 - https

# tags are used for organizing operations
tags:
- name: default
  description: Secured Admin-only calls

paths:
  /workflow-engines:
    get:
      summary: Removed from API
      operationId: searchWorkFlowEngines
      description: |
        Retrieve metadata information of all the workflow engines in the system.
        (Removed from API)
      responses:
        '410':
          description: Gone

host: localhost:9443
basePath: /t/{tenant-domain}/api/server/v1
